apiVersion: apps/v1
kind: Deployment
metadata:
    name: madome-runner
spec:
    replicas: 1
    selector:
        matchLabels:
            app: madome-runner
    template:
        metadata:
            labels:
                app: madome-runner
        spec:
            volumes:
                - name: dockersock
                  hostPath:
                      path: /var/run/docker.sock
                - name: workdir
                  hostPath:
                      path: /runner
            containers:
                - name: runner
                  image: myoung34/github-runner:latest
                  resources:
                      limits:
                          memory: "256Mi"
                          cpu: "250m"
                  env:
                      - name: ACCESS_TOKEN
                        valueFrom:
                            configMapKeyRef:
                                name: madome-runner-secret
                                key: access_token
                      - name: RUNNER_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: madome-runner-secret
                                key: runner_name
                      - name: RUNNER_SCOPE
                        value: "org"
                      - name: ORG_NAME
                        value: "Project-Madome"
                      - name: RUNNER_NAME_PREFIX
                        value: madome-runner
                      - name: RUNNER_WORKDIR
                        value: /runner
                      - name: LABELS
                        valueFrom:
                            configMapKeyRef:
                                name: madome-runner-secret
                                key: labels
                  command:
                      - /bin/bash
                      - -c
                      - |
                          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&
                          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256" &&
                          echo "$(<kubectl.sha256) kubectl" | sha256sum --check &&
                          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl &&
                          kubectl version --client

                  volumeMounts:
                      - name: dockersock
                        mountPath: /var/run/docker.sock
                      - name: workdir
                        mountPath: /runner
